pipeline {
    agent any

    stages {
        stage('Get Dependencies') {
            steps {
                echo 'Building..'
                sh '''
                node -v
                npm install
                '''
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}