pipeline {
    agent any

    stages {
        stage('Get Dependencies') {
            steps {
                echo 'Building..'
                sh '''
                node -v
                npm -v
                wget https://github.com/ali85j/fxc-web-v2/blob/master/node_modules.tar.gz
                tar -pzxf node_modules node_modules.tar.gz
                '''
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                npm run test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}